// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3yF_87GcVlYA6CHLrJuPwNIKRqqQmGEM',
    appId: '1:775867159923:web:02457adb633aa55f716106',
    messagingSenderId: '775867159923',
    projectId: 'book-list-295cd',
    authDomain: 'book-list-295cd.firebaseapp.com',
    storageBucket: 'book-list-295cd.appspot.com',
    measurementId: 'G-1H11S2RT87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0MScvVvMfznyXoJlAElqIlN-TmCQFO_I',
    appId: '1:775867159923:android:b8c752abc87c876c716106',
    messagingSenderId: '775867159923',
    projectId: 'book-list-295cd',
    storageBucket: 'book-list-295cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASWxPQuJllbpsWC6S796QysN9_Aqd9ZJc',
    appId: '1:775867159923:ios:ab6f42a74eb6dfce716106',
    messagingSenderId: '775867159923',
    projectId: 'book-list-295cd',
    storageBucket: 'book-list-295cd.appspot.com',
    iosBundleId: 'com.example.book',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASWxPQuJllbpsWC6S796QysN9_Aqd9ZJc',
    appId: '1:775867159923:ios:27987ca048e2bd36716106',
    messagingSenderId: '775867159923',
    projectId: 'book-list-295cd',
    storageBucket: 'book-list-295cd.appspot.com',
    iosBundleId: 'com.example.book.RunnerTests',
  );
}
